=== SalsaAddict/emusicality-v5/src/assets/schemas/breakdown.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "IGroup": {
            "additionalProperties": {
                "items": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/ITrack"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "type": "array"
            },
            "title": "IGroup",
            "type": "object"
        },
        "IMeasure": {
            "additionalProperties": false,
            "properties": {
                "framework": {
                    "title": "framework",
                    "type": "string"
                },
                "length": {
                    "title": "length",
                    "type": "number"
                },
                "warning": {
                    "title": "warning",
                    "type": "boolean"
                }
            },
            "title": "IMeasure",
            "type": "object"
        },
        "ISection": {
            "additionalProperties": false,
            "properties": {
                "description": {
                    "title": "description",
                    "type": "string"
                },
                "framework": {
                    "title": "framework",
                    "type": "string"
                },
                "measures": {
                    "anyOf": [
                        {
                            "items": {
                                "anyOf": [
                                    {
                                        "$ref": "#/definitions/IMeasure"
                                    },
                                    {
                                        "type": [
                                            "string",
                                            "number"
                                        ]
                                    }
                                ]
                            },
                            "type": "array"
                        },
                        {
                            "type": "number"
                        }
                    ],
                    "title": "measures"
                }
            },
            "required": [
                "description",
                "measures"
            ],
            "title": "ISection",
            "type": "object"
        },
        "ITrack": {
            "additionalProperties": false,
            "properties": {
                "description": {
                    "title": "description",
                    "type": "string"
                },
                "filename": {
                    "title": "filename",
                    "type": "string"
                }
            },
            "required": [
                "description",
                "filename"
            ],
            "title": "ITrack",
            "type": "object"
        }
    },
    "properties": {
        "$schema": {
            "enum": [
                "../../schemas/breakdown.json"
            ],
            "title": "$schema",
            "type": "string"
        },
        "beatsPerMeasure": {
            "title": "beatsPerMeasure",
            "type": "number"
        },
        "sections": {
            "items": {
                "$ref": "#/definitions/ISection"
            },
            "title": "sections",
            "type": "array"
        },
        "startOffset": {
            "title": "startOffset",
            "type": "number"
        },
        "tracks": {
            "items": {
                "anyOf": [
                    {
                        "$ref": "#/definitions/ITrack"
                    },
                    {
                        "$ref": "#/definitions/IGroup"
                    },
                    {
                        "type": "string"
                    }
                ]
            },
            "title": "tracks",
            "type": "array"
        }
    },
    "required": [
        "$schema",
        "beatsPerMeasure",
        "sections",
        "tracks"
    ],
    "type": "object"
}

=== SalsaAddict/emusicality-v5/src/assets/songs/esoesamor/breakdown.json
{
  "$schema": "../../schemas/breakdown.json",
  "startOffset": 1.8,
  "beatsPerMeasure": 8,
  "tracks": [
    "Vocals",
    {
      "Percussion": ["Bongo", {
        "description": "Gu√Øra",
        "filename": "guira.mp3"
      }]
    },
    {
      "Guitars": ["Requinto", "Segunda", "Bass"]
    }
  ],
  "sections": [{
      "description": "Intro",
      "measures": [0, 0, 4]
    },
    {
      "description": "Verse",
      "framework": "Derecho",
      "measures": [0, 0, 0, 0, -1, 0, 0, 0, -1]
    },
    {
      "description": "Bridge",
      "measures": [-1, -1, 4]
    },
    {
      "description": "Chorus",
      "measures": ["Majao", 0, "Derecho", -1, "Majao", 0, "Derecho", -1]
    },
    {
      "description": "Verse",
      "framework": "Derecho",
      "measures": [0, 0, 0, 0, -1, 0, 0, 0, -1]
    },
    {
      "description": "Bridge",
      "measures": [-1, -1, 4]
    },
    {
      "description": "Chorus",
      "measures": ["Majao", 0, "Derecho", -1, "Majao", 0, "Derecho", -1]
    },
    {
      "description": "Mambo",
      "measures": [{
        "framework": "Derecho"
      }, 4, 0, -1, {
        "framework": "Majao"
      }, 0, 4, 0, 0, 4]
    },
    {
      "description": "Verse",
      "framework": "Derecho",
      "measures": [0, 0, 0, 0, 4]
    },
    {
      "description": "Chorus",
      "measures": ["Majao", 0, "Derecho", -1, "Majao", 0, "Derecho", 4]
    },
    {
      "description": "Outro",
      "measures": [-1, 4]
    }
  ]
}
